const teachersData = [
  {
    id: 1,
    name: "Amina Yusuf",
    subject: "Mathematics",
    department: "Science",
    experience: "5 Years",
    class: "SS2A",
    bio: "Simplifies complex math concepts for students.",
    expertise: "Algebra, Geometry, Calculus, Statistics, Problem Solving",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    email: "math@mail.com",
    education: "B.Sc. Physics, University of Nigeria",
    date: "2012-2016",
    education2: "Postgraduate Diploma in Education",
    date2: "2017-2018",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 2,
    name: "Daniel Okafor",
    expertise: "Mechanics, Electricity, Magnetism, Waves, Practical Physics",
    subject: "Physics",
    department: "Science",
    experience: "7 Years",
    class: "SS3B",
    bio: "Makes Physics easy through practical teaching.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    email: "physics@mail.com",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
    education: "B.Sc. Physics, University of Nigeria",
    date: "2012-2016",
    education2: "Postgraduate Diploma in Education",
    date2: "2017-2018",
  },
  {
    id: 3,
    name: "Blessing Ade",
    subject: "English Language",
    expertise:
      "Grammar, Literature, Creative Writing, Communication Skills, Public Speaking",
    department: "Arts",
    experience: "4 Years",
    class: "SS1A",
    bio: "Improves grammar and communication skills.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    email: "english@mail.com",
    education: "B.A. English Language, Obafemi Awolowo University",
    date: "2015-2019",
    education2: "Teaching Certification",
    date2: "2020-2021",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 4,
    name: "Michael Johnson",
    subject: "Chemistry",
    department: "Science",
    experience: "6 Years",
    expertise:
      "Organic Chemistry, Inorganic Chemistry, Laboratory Analysis, Chemical Reactions, Biochemistry",
    class: "SS2B",
    bio: "Specialist in organic and inorganic chemistry.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    email: "chemistry@mail.com",
    education: "B.Sc. Chemistry, University of Ilorin",
    date: "2011-2015",
    education2: "M.Sc. Organic Chemistry",
    date2: "2016-2018",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 5,
    name: "Fatima Bello",
    subject: "Biology",
    department: "Science",
    experience: "5 Years",
    class: "SS3A",
    expertise: "Human Biology, Genetics, Ecology, Microbiology, Anatomy",
    bio: "Focuses on human biology and life sciences.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    education: "B.Sc. Biology, Ahmadu Bello University",
    date: "2013-2017",
    education2: "M.Sc. Human Biology",
    date2: "2018-2020",
    email: "Historia@mail.com",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 6,
    name: "Chinedu Eze",
    subject: "Geography",
    department: "Arts",
    experience: "8 Years",
    expertise:
      "Physical Geography, Human Geography, GIS, Environmental Studies, Cartography",
    class: "SS2C",
    bio: "Expert in physical and human geography.",
    location: "Jakarta, califonia",
    contact: "+12 546780998",
    education: "B.Sc. Geography, University of Benin",
    date: "2010-2014",
    education2: "Diploma in Environmental Studies",
    date2: "2015-2016",
    email: "Historia@mail.com",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 7,
    name: "Grace Williams",
    subject: "Literature",
    department: "Arts",
    experience: "6 Years",
    expertise: "English Literature, Poetry, Drama, Fiction, Literary Analysis",
    class: "SS1B",
    bio: "Passionate about English literature and poetry.",
    location: " Indonesia",
    contact: "+12 345 6789 0",
    email: "litrature@mail.com",
    education: "B.A. Literature, University of Ibadan",
    date: "2014-2018",
    education2: "Creative Writing Certification",
    date2: "2019-2020",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 8,
    name: "Samuel Peters",
    subject: "Economics",
    department: "Commercial",
    experience: "5 Years",
    expertise:
      "Microeconomics, Macroeconomics, Financial Markets, Business Economics, International Trade",
    class: "SS3C",
    bio: "Teaches economic principles and real-world applications.",
    location: "Indonesia",
    contact: "+12 345 6789 0",
    email: "economics@mail.com",
    education: "B.Sc. Economics, Covenant University",
    date: "2012-2016",
    education2: "MBA in Finance",
    date2: "2017-2019",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 9,
    name: "Deborah Kings",
    subject: "Computer Science",
    department: "Science",
    experience: "4 Years",
    class: "SS2D",
    expertise:
      "Programming, Web Development, Databases, Networking, Digital Literacy",
    bio: "Specialist in programming and digital literacy.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    email: "computer@mail.com",
    education: "B.Sc. Computer Science, University of Lagos",
    date: "2016-2020",
    education2: "Full Stack Web Development Certification",
    date2: "2021-2022",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 10,
    name: "Ibrahim Musa",
    subject: "History",
    department: "Arts",
    experience: "9 Years",
    expertise:
      "African History, World History, Ancient Civilizations, Political History, Historical Research",
    class: "SS3D",
    bio: "Brings history to life with storytelling.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    email: "history@mail.com",
    education: "B.A. History, Bayero University",
    date: "2008-2012",
    education2: "M.A. African History",
    date2: "2013-2015",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
  {
    id: 11,
    name: "Sophia James",
    subject: "Art",
    department: "Arts",
    expertise: "Fine Arts, Painting, Drawing, Sculpture, Visual Design",
    experience: "3 Years",
    expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    class: "SS1C",
    bio: "Encourages creativity and visual expression.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    education: "History Major, University Akademi Historia",
    date: "2013-2017",
    education2: "History Major, University Akademi Historia",
    date2: "2013-2017",
    email: "art@mail.com",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
    education: "History Major, University Akademi Historia",
    date: "2013-2017",
    education2: "History Major, University Akademi Historia",
    date2: "2013-2017",
  },
  {
    id: 12,
    name: "Peter Collins",
    subject: "Agricultural Science",
    department: "Science",
    experience: "6 Years",
    class: "SS2E",
    bio: "Teaches modern farming and agriculture techniques.",
    location: "Jakarta, Indonesia",
    contact: "+12 345 6789 0",
    email: "agric@mail.com",
    education: "B.Sc. Agricultural Science, Federal University of Agriculture",
    date: "2012-2016",
    education2: "M.Sc. Crop Science",
    expertise:
      "Crop Science, Animal Husbandry, Soil Science, Agricultural Technology, Farm Management",
    date2: "2017-2019",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
  },
];

export default teachersData;
